thin-edge/thin-edge.io_examples

zigbee2mqtt/README.md, zigbee2mqtt/config/configuration.yaml, zigbee2mqtt/config/extension/thin-edge-extension.js, zigbee2mqtt/docker-compose.yaml
This pull requests adds instructions and sample configurations on how to use thin-edge.io together with Zigbee2MQTT.
=> Add Zigbee2MQTT sample

StreamingAnalytics/LimitedBandwidth/README.md, StreamingAnalytics/LimitedBandwidth/config/CorrelatorConfig.yaml, StreamingAnalytics/LimitedBandwidth/eventdefinitions/EventDefs.mon
I've fixed and improved various parts of the readme for this sample and removed some lines from the config that are not necessary due to the use of engine_deploy.
=> Improved instructions for StreamingAnalytics/LimitedBandwidth sample

StreamingAnalytics/LimitedBandwidth/README.md
To avoid potential issue with engine_deploy
=> Small tweak to StreamingAnalytics/LimitedBandwidth README

.gitmodules, bme280/.gitignore, bme280/Makefile, bme280/README.md, bme280/cloud_bme280.c, bme280/local_bme280.c, bme280/tedge_bme280.c
Code used for the meetup to demo thin-edge integration with c application.
=> Code used for the meetup (c integration demo)

StreamingAnalytics/LimitedBandwidth/README.md, StreamingAnalytics/README.md, StreamingAnalytics/src/service/apama
Made some more improvements and corrections to the Streaming Analytics readme files following some more internal review.
None
=> Streaming Analytics improvements

docker-alpine/Dockerfile
The Dockerfile uses always the latest version of the offical provided alpine image. As alpine project can publishs new releases with potential backward incompatibilities, those can break that example.
So happened with current latest alpine, where "/sbin/init" fails since it's link destination "/sbin/openrc-init" is gone:
```
$ docker run -it -d --name=tedge tedge_docker_alpine
Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/sbin/init": stat /sbin/init: no such file or directory: unknown
Error: failed to start containers: tedge
```
_Put an `x` in the boxes that apply. You can also fill these out after creating the …
=> stick alpine to a fixed valid version

child-device-agent/README.md, child-device-agent/c8y-configuration-plugin.toml, child-device-agent/child_device_agent.py, child-device-agent/requirements.txt
Child device configuration management agent prototype to demonstrate child device configuration management capabilities of thin-edge with Cumulocity.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
=> Child device configuration management agent prototype

StreamingAnalytics/LimitedBandwidth/README.md, StreamingAnalytics/LowLatencyCommandAndControl/README.md, StreamingAnalytics/README.md, StreamingAnalytics/ResourceMonitoring/README.md
The README files for Apama's Thin Edge samples need updating now Apama is providing Debian packages to install Apama on devices.
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
=> Update Apama Thin Edge sample documentation

node-red-management-plugin/node-red-devicemanagement-plugin/README.md, node-red-management-plugin/node-red-devicemanagement-plugin/src/node-red-device.module.ts, node-red-management-plugin/node-red-devicemanagement-plugin/src/node-red-tab.component.html, node-red-management-plugin/node-red-devicemanagement-plugin/src/node-red-tab.component.ts, node-red-management-plugin/node-red-devicemanagement-plugin/src/shared/node-red-flows.service.ts, node-red-management-plugin/node-red-devicemanagement-plugin/src/shared/node-red-models.ts, node-red-management-plugin/node-red-devicemanagement-plugin/src/shared/realtimeHelper.service.ts
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
- [ x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [ …
=> Update node red management UI

child-device-agent/README.md, child-device-agent/child_device_agent.py
Update child-device_connector to implement firmware management specification.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
=> Firmware update support for child-device-connector

StreamingAnalytics/LimitedBandwidth/README.md, StreamingAnalytics/LowLatencyCommandAndControl/README.md, StreamingAnalytics/README.md, StreamingAnalytics/ResourceMonitoring/README.md
This change fixes malformed copyright notices in our thin-edge documentation files. No other change is required for Apama release 10.15.3.
=> Commit for release 10.15.3.0

sense-hat/README.md, sense-hat/thin_edge_sense_hat/thin_edge_client.py
Update example to use thin-edge.io v1 topics (e.g. `tedge/measurements` => `te/device/main///m/`).
The link to the thin-edge.io installation instructions was also updated.
=> chore: update sensehat example to use thin-edge.io v1 topics

StreamingAnalytics/LimitedBandwidth/project/monitors/ThinEdgeIoExample.mon, StreamingAnalytics/README.md, StreamingAnalytics/ResourceMonitoring/README.md, StreamingAnalytics/ResourceMonitoring/project/eventdefinitions/ResourceMonitoringEventDefinitions.mon, StreamingAnalytics/src/quickstart/project/monitors/TedgeDemoMonitor.mon
Updating the MQTT topics used in the examples, e.g. rename `tedge/measurements` => `te/device/main///m/`).
Old links to the thin-edge.io documentation have also been updated (though one or two still remain, however there is work needed on the thin-edge.io side first before replacing the "installing software" link)
=> chore: update apama examples to use thin-edge.io v1 topics

config2MQTT-watchdog/README.md, management-ui/README.md, node-red-management-plugin/README.md, opcua-solution/README.md
Fix various typos in documentation
=> docs: fix typos

node-red-management-plugin/README.md
Update instructions to use the update docs and removing outdated instructions.
Minor formatting improvements were also made to make the raw markdown easier to read.
=> docs: update nodered example instructions

zigbee2mqtt/config/extension/thin-edge-extension.js
Update zigbee example to use the thin-edge.io v1 MQTT topics, e.g. `tedge/measurements` => `te/device/main///m/`.
=> chore: update zigbee example to use thin-edge.io MQTT topic structure to v1

bme280/tedge_bme280.c
Update example to use thin-edge.io v1 topics (e.g. `tedge/measurements` => `te/device/main///m/`).
=> chore: update bme example to use thin-edge.io v1 MQTT topics

StreamingAnalytics/LimitedBandwidth/demo_publisher.py, StreamingAnalytics/LowLatencyCommandAndControl/test_publisher.py, StreamingAnalytics/ResourceMonitoring/resource-monitor.py
General formatting and minor pylint fixes to make sure the formatting is normalized (e.g. using one style of quotes, and not a mix, import statement order etc.)
No functionality was changed.
=> chore: normalize formatting using black and fix minor pylint warnings

child-device-agent/README.md
Add deprecation notice to the example but keep it as it is still referenced in older snapshots of the official thin-edge.io documentation (to prevent creating broken links).
A link to the new project, [python-tedge-agent](https://github.com/thin-edge/python-tedge-agent) has also been added.
=> docs(child-device-agent): add deprecation notice

opcua-solution/docker-compose.yml
Minor fix which corrects the exposed port (as docker stats that the expose directive should be the container port and not the host's port, see [docs on the expose directive](https://docs.docker.com/compose/compose-file/compose-file-v3/#expose)).
=> fix: update expose port to use the internal port

opcua-docker/README.md
Update opcua-docker example to include a note that armv7 linux platforms are also supported.
=> docs(opcua-docker): add note about supporting armv7 linux platform

.github/CODEOWNERS
@jdoc-sag will be leaving us, so I'll take over ownership here. I assume you might need to add me to the repository in some form.
=> CODEOWNERS: replace /StreamingAnalytics/ code owner

StreamingAnalytics/README.md
Apama Docker images are moving locations, so need to be updated.
In addition, we've changed the way we package our releases, so update a brief note here.
=> Update Streaming Analytics samples for new Docker image location

CONTRIBUTING.md, CONTRIBUTOR-LICENSE-AGREEMENT.md, node-red-management-plugin/README.md, node-red-management-plugin/node-red-devicemanagement-plugin/README.md, webrtc-webcam/README.md, webrtc-webcam/package.json
Update company references including:
* Copyright
* Tech community references
* Github org references
=> docs: update company references

README.md
Remove reference to the x/twitter badge since it is no longer actively used.
=> docs: remove x/twitter badge

.github/CODEOWNERS
Update the team reference in the CODEOWNERS doc after renaming it.
=> chore: update github team reference after renaming

.github/CODEOWNERS
Update CODEOWNERS for Streaming Analytics
=> Update CODEOWNERS for Streaming Analytics
